### ISSUE TITLE
Interoperability issue with RTI

### ISSUE THREAD

**Issue by LanderU** [aliasrobotics/aztarna#38]
Got this error when running `--daemon` option against RTI pub/sub.

```bash
root@alias:/aztarna# aztarna -t ros2 --daemon -d 1
Scanning the network...
Exploring ROS_DOMAIN_ID: 1 for nodes
[ERROR] [rmw_fastrtps_shared_cpp]: Unable to find GUID for node: talker
aztarna.cmd - Exception occurred during execution
Traceback (most recent call last):
  File "/usr/local/bin/aztarna", line 11, in <module>
    load_entry_point('aztarna==1.2.2', 'console_scripts', 'aztarna')()
  File "/usr/local/lib/python3.6/dist-packages/aztarna-1.2.2-py3.6.egg/aztarna/cmd.py", line 100, in main
    off the received input, and dispatch to action methods, passing them
  File "/usr/local/lib/python3.6/dist-packages/aztarna-1.2.2-py3.6.egg/aztarna/cmd.py", line 92, in main
    self.stdout = stdout
  File "/usr/local/lib/python3.6/dist-packages/aztarna-1.2.2-py3.6.egg/aztarna/ros/ros2/scanner.py", line 474, in scan
  File "/usr/local/lib/python3.6/dist-packages/aztarna-1.2.2-py3.6.egg/aztarna/ros/ros2/scanner.py", line 131, in ros2cli_api
  File "/usr/local/lib/python3.6/dist-packages/aztarna-1.2.2-py3.6.egg/aztarna/ros/ros2/scanner.py", line 162, in ros2node
  File "/opt/ros/dashing/lib/python3.6/site-packages/ros2node/api/__init__.py", line 68, in get_subscriber_info
    return get_topics(remote_node_name, node.get_subscriber_names_and_types_by_node)
  File "/opt/ros/dashing/lib/python3.6/site-packages/ros2node/api/__init__.py", line 59, in get_topics
    names_and_types = func(node.name, node.namespace)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/node.py", line 1449, in get_subscriber_names_and_types_by_node
    capsule, no_demangle, node_name, node_namespace)
RuntimeError: Failed to get_subscriber_names_and_types: Unable to find GUID for node , at /tmp/binarydeb/ros-dashing-rmw-fastrtps-shared-cpp-0.7.5/src/rmw_node_info_and_types.cpp:87
```

**Comment by LanderU** [comment]
**NOTE:** This only happen with RTI, tested implementations, CycloneDDS, OpensSplice, Fast-RTPS.

**Comment by LanderU** [comment]
Issue to track: https://github.com/eProsima/Fast-RTPS/issues/800#issuecomment-547436950
